services:
  educloud-postgres:
    container_name: educloud-postgres
    image: postgres:16.6
    restart: always
    hostname: educloud-postgres
    environment:
      POSTGRES_USER: educloud
      POSTGRES_PASSWORD: educloud
      POSTGRES_DB: educloud
    volumes:
      - educloud_db:/var/lib/postgresql/data
    networks:
      - educloud

  backend:
    container_name: educloud-backend
    image: ghcr.io/pollak-projects/educloud-ts-server/app:latest
    restart: always
    ports:
      - "7670:3300"
    depends_on:
      - educloud-postgres
    networks:
      - educloud
    environment:
      PORT=3300
      DB_HOST=educloud-postgres
      DB_PORT=5432
      DB_USER=educloud
      DB_PASSWORD=educloud
      DB_NAME=educloud
      DEV=true
      JWT_SECRET=secret

networks:
  educloud:

volumes:
  educloud_db:
