name: Docker Build & Publish to github packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Docker Image 🏗️
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4
        with:
          repository: pollak-projects/educloud-ts-server
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry 🚢
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pollak-projects/educloud-ts-server/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  triggerUpdate:
    name: Trigger Update 🔄
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Call Webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}